version: 2
jobs:
   build:
     docker:
       - image: koppor/texlive:v1.2.0
     steps:
       - checkout
       # prepare papers: extract hyperlink information (pax)
       - run: ./prepare-papers.sh
       # generate paper.tex out of paper.docx
       - run: cd papers && ./add_tex_via_docx.sh
       # generate final proceedings.tex based on the information of each paper.tex file
       - run: cd papers && python ../addAuthTiProduction.py ../proceedings.template ../proceedings.tex */paper.tex
       # steps as in make-proceedings.sh
       - run: pdflatex -synctex=1 proceedings
       - run: pdflatex -synctex=1 proceedings
       - run: sed -i "s/\\\\IeC //g" proceedings.bib
       - run: biber proceedings
       - run: pdflatex -synctex=1 proceedings
       - run: texindy proceedings.idx
       - run: pdflatex -synctex=1 proceedings
       - run: pdflatex -synctex=1 proceedings
       - run: sed -i "s/\\\\IeC //g" proceedings.bib
       - run: sed -i "s/\\\\textunderscore //g" proceedings.bib
       - run: sed -i "s/\\\\IeC //g" proceedings.csv
       - run: sed -i "s/ ;/;/g" proceedings.csv
       # extract meta data
       - run: cp proceedings.csv meta-extract/
       - run: cd meta-extract && python metaExtract.py papers.csv ws.csv proceedings.csv
       # shrink proceedings
       - run: mv proceedings.pdf proceedings-large.pdf
       - run: ./shrinkpdf.sh proceedings-large.pdf proceedings.pdf
       # slice proceedings
       - run: cp proceedings.pdf proceedings.csv slicing/
       - run: cd slicing && pdfjam --trim "27mm 31mm 27mm 31mm" --clip true --suffix cropped proceedings.pdf
       - run: cd slicing && python slicing.py proceedings-cropped.pdf proceedings.csv
       # collect final files
       - run: mkdir result && mv slicing/parts/*.pdf result/ && mv slicing/proceedings-cropped.pdf result/proceedings-final.pdf && mv meta-extract/meta_extract.csv result/
       - store_artifacts:
           path: result
